### PR TITLE
Fix versioning so we do not include pre-releases as the latest version

### LINKED ISSUE #276: Do not include pre-release versions of test wrappers when setting the latest version.
Exclude pre-releases as being candidate for the latest test wrapper version.

### PR DESCRIPTION
**Pull request by dvalinrh**
# Description
Prevents pulling in pre-releases when we have asked to update the test versions

# Before/After Comparison
Before: We could pull in a pre-release version as an official version.
After: We will pull in the version that is marked as the latest.

# Clerical Stuff
This closes #276 

Relates to JIRA: RPOPC-584

# Testing
Verified the pre-release versions do not turn up.
Verified still can use a pre-release version.
Verfiied when updating the versions, the pre-release versions are not considered.

### CODE REVIEW

**Review by kdvalin — CHANGES_REQUESTED** [review]
Update install script with `gh`

File: bin/install.sh [hunk 1]
```diff
@@ -51,7 +51,7 @@ else
 fi
 
 # check for and install system packages
-packages=(ansible-core git jq python python3-pip terraform unzip wget)
+packages=(ansible-core git jq python python3-pip terraform unzip wget gh)
```
Comment (kdvalin) [inline bin/install.sh]: `gh` is not available in default RHEL repos, see https://github.com/cli/cli/blob/trunk/docs/install_linux.md#rpm

Comment (kdvalin) [reply bin/install.sh]: It is available in EPEL though

Comment (dvalinrh) [reply bin/install.sh]: Available several means, including epel

Last metadata expiration check: 2:06:20 ago on Tue 02 Sep 2025 10:01:59 AM EDT.
gh-2.65.0-1.x86_64 : GitHub’s official command line tool.
Repo        : @System
Matched from:
Filename    : /usr/bin/gh

gh-2.76.1-1.el9.x86_64 : GitHub's official command line tool
Repo        : epel
Matched from:
Filename    : /usr/bin/gh
Filename    : /usr/share/bash-completion/completions/gh
Filename    : /usr/share/doc/gh
Filename    : /usr/share/licenses/gh

gh-2.78.0-1.aarch64 : GitHub’s official command line tool.
Repo        : gh-cli
Matched from:
Filename    : /usr/bin/gh
Filename    : /usr/share/bash-completion/completions/gh

Comment (kdvalin) [reply bin/install.sh]: The `@System` means it was installed.

The `gh-cli` repo is an added repo, but not shipped by default on RHEL.

If we need EPEL we should document that somewhere (or install the repo automagically)

**Review by kdvalin — APPROVED** [review]
LGTM
