### PR TITLE
Installer patch - fix yq version, correct ansible package name

### LINKED ISSUE #83: install script needs work
install script needs to
 1) Install specific versions of software
 2) Bail on errors

What i had to do earlier (edited) 
pip install 'ansible==v2.9.6'
pip install 'yq==2.10.0'
pip install jinja2==3.0.3
That was just version pieces after I ran your install script.
I had to do numerous other package installs  also.  Best way to get it all, is to install a machine clean with rhel 9, and then try things (I was on a lab machine)

### PR DESCRIPTION
**Pull request by grdumas**
Changes Python package installation to no longer install latest version of yq because newer versions will break Zathras functionality.

Also corrects package name 'ansible' to 'ansible-core'.

### CODE REVIEW

File: bin/install.sh [hunk 1]
```diff
@@ -69,14 +69,15 @@ for package in "${packages[@]}"; do
...
+        echo "package $package is not installed and not available."
     fi
 
 done
 
 
 # pip install requirements
-pip3 install -U boto boto3 yq --user
+pip3 install boto boto3 --user
+pip3 install 'yq==2.10.0'
```
Comment (kdvalin) [inline bin/install.sh]: Is there a reason why `--user` was dropped for this pip install?

**Review by kdvalin — CHANGES_REQUESTED** [review]

File: bin/install.sh (hunk 1 above)
Comment (grdumas) [reply bin/install.sh]: No reason, good catch. Fixed in subsequent commit.

**Review by kdvalin — APPROVED** [review]
LGTM
